services:
  my_server:
    build: .
    image: my_server
    container_name: my_server
    hostname: my_server
    networks:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    volumes:
      - ./server/nginx/nginx2.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:8080"
    depends_on:
      - my_server
    networks:
      - nginx

networks:
  nginx:
    driver: bridge
